// frontend/src/app/pages/workbench-page/ask-about-response/ask-about-response.component.ts
import { Component, Input, inject, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { ApiService } from '../../../core/services/api.service'
import { ApiError } from '../../../core/services/api-error'
import type { ProbeResult } from '../../../core/models'

/**
 * Consulta/análise em linguagem natural sobre a resposta real (ex: "qual o
 * valor do campo elevation?"). Deliberadamente distinto do assistente de
 * regras de negócio: aqui a IA só responde uma pergunta de leitura sobre o
 * JSON observado — nunca cria uma Rule, nunca influencia PASS/FAIL. Porta
 * 1:1 de components/AskAboutResponse.tsx.
 */
@Component({
  selector: 'app-ask-about-response',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="mt-3 border-t border-border pt-3">
      <p class="mb-2 text-sm font-medium text-foreground-muted">🤖 Pergunte sobre esta resposta</p>
      @if (history().length > 0) {
        <ul class="mb-3 space-y-2">
          @for (h of history(); track $index) {
            <li class="text-sm">
              <p class="font-medium text-foreground">Você: {{ h.q }}</p>
              <p class="text-foreground-muted">{{ h.a }}</p>
            </li>
          }
        </ul>
      }
      <form class="flex gap-2" (submit)="onSubmit($event)">
        <input
          class="input"
          placeholder="Ex: &quot;qual o valor do campo elevation?&quot;"
          [ngModel]="question()"
          (ngModelChange)="question.set($event)"
          name="question"
        />
        <button class="btn-secondary" [disabled]="!question().trim() || pending()" type="submit">
          {{ pending() ? '...' : 'Perguntar' }}
        </button>
      </form>
      @if (error()) {
        <p class="mt-1 text-xs text-danger">{{ error() }}</p>
      }
    </div>
  `,
})
export class AskAboutResponseComponent {
  private api = inject(ApiService)

  @Input({ required: true }) probe!: ProbeResult

  question = signal('')
  pending = signal(false)
  error = signal<string | null>(null)
  history = signal<{ q: string; a: string }[]>([])

  async onSubmit(e: Event) {
    e.preventDefault()
    const q = this.question().trim()
    if (!q) return
    this.pending.set(true)
    this.error.set(null)
    try {
      const result = await this.api.aiAnswerQuestion(q, this.probe)
      this.history.set([...this.history(), { q, a: result.answer }])
      this.question.set('')
    } catch (err) {
      this.error.set(err instanceof ApiError ? err.message : (err as Error).message)
    } finally {
      this.pending.set(false)
    }
  }
}

// frontend/src/components/AskAboutResponse.tsx
import { useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import { aiAnswerQuestion } from '../lib/api'
import type { ProbeResult } from '../types'

/**
 * Consulta/análise em linguagem natural sobre a resposta real (ex: "qual o
 * valor do campo elevation?"). Isto é deliberadamente distinto do
 * assistente de regras de negócio: aqui a IA só responde uma pergunta de
 * leitura sobre o JSON observado — nunca cria uma Rule, nunca influencia
 * PASS/FAIL.
 */
export default function AskAboutResponse({ probe }: { probe: ProbeResult }) {
  const [question, setQuestion] = useState('')
  const [history, setHistory] = useState<{ q: string; a: string }[]>([])

  const mutation = useMutation({
    mutationFn: (q: string) => aiAnswerQuestion(q, probe),
    onSuccess: (result, q) => {
      setHistory((h) => [...h, { q, a: result.answer }])
      setQuestion('')
    },
  })

  return (
    <div className="mt-3 border-t border-slate-100 pt-3">
      <p className="mb-2 text-sm font-medium text-slate-600">🤖 Pergunte sobre esta resposta</p>
      {history.length > 0 && (
        <ul className="mb-3 space-y-2">
          {history.map((h, i) => (
            <li key={i} className="text-sm">
              <p className="font-medium text-slate-700">Você: {h.q}</p>
              <p className="text-slate-500">{h.a}</p>
            </li>
          ))}
        </ul>
      )}
      <form
        className="flex gap-2"
        onSubmit={(e) => {
          e.preventDefault()
          if (question.trim()) mutation.mutate(question.trim())
        }}
      >
        <input
          className="input"
          placeholder='Ex: "qual o valor do campo elevation?"'
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
        />
        <button className="btn-secondary" disabled={!question.trim() || mutation.isPending} type="submit">
          {mutation.isPending ? '...' : 'Perguntar'}
        </button>
      </form>
      {mutation.isError && <p className="mt-1 text-xs text-rose-600">{(mutation.error as Error).message}</p>}
    </div>
  )
}
