// frontend/src/app/shared/key-value-editor/key-value-editor.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'
import { FormsModule } from '@angular/forms'
import type { Pair } from '../../core/utils/pairs'

@Component({
  selector: 'app-key-value-editor',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="space-y-2">
      @for (p of pairs; track $index) {
        <div class="flex gap-2">
          <input
            class="input mono flex-1"
            [placeholder]="keyPlaceholder"
            [ngModel]="p.key"
            (ngModelChange)="update($index, 'key', $event)"
          />
          <input
            class="input mono flex-1"
            [placeholder]="valuePlaceholder"
            [ngModel]="p.value"
            (ngModelChange)="update($index, 'value', $event)"
          />
          <button type="button" class="btn-secondary px-2" (click)="remove($index)">✕</button>
        </div>
      }
      <button type="button" class="link text-sm" (click)="add()">+ adicionar</button>
    </div>
  `,
})
export class KeyValueEditorComponent {
  @Input({ required: true }) pairs: Pair[] = []
  @Input() keyPlaceholder = 'nome'
  @Input() valuePlaceholder = 'valor'
  @Output() pairsChange = new EventEmitter<Pair[]>()

  update(i: number, field: 'key' | 'value', value: string) {
    const next = [...this.pairs]
    next[i] = { ...next[i], [field]: value }
    this.pairsChange.emit(next)
  }

  remove(i: number) {
    this.pairsChange.emit(this.pairs.filter((_, idx) => idx !== i))
  }

  add() {
    this.pairsChange.emit([...this.pairs, { key: '', value: '' }])
  }
}

// frontend/src/components/KeyValueEditor.tsx
interface Pair {
  key: string
  value: string
}

export function recordToPairs(record: Record<string, string>): Pair[] {
  return Object.entries(record).map(([key, value]) => ({ key, value }))
}

export function pairsToRecord(pairs: Pair[]): Record<string, string> {
  const out: Record<string, string> = {}
  for (const p of pairs) {
    if (p.key.trim()) out[p.key.trim()] = p.value
  }
  return out
}

export default function KeyValueEditor({
  pairs,
  onChange,
  keyPlaceholder = 'nome',
  valuePlaceholder = 'valor',
}: {
  pairs: Pair[]
  onChange: (pairs: Pair[]) => void
  keyPlaceholder?: string
  valuePlaceholder?: string
}) {
  const update = (i: number, field: 'key' | 'value', value: string) => {
    const next = [...pairs]
    next[i] = { ...next[i], [field]: value }
    onChange(next)
  }
  const remove = (i: number) => onChange(pairs.filter((_, idx) => idx !== i))
  const add = () => onChange([...pairs, { key: '', value: '' }])

  return (
    <div className="space-y-2">
      {pairs.map((p, i) => (
        <div key={i} className="flex gap-2">
          <input
            className="input mono flex-1"
            placeholder={keyPlaceholder}
            value={p.key}
            onChange={(e) => update(i, 'key', e.target.value)}
          />
          <input
            className="input mono flex-1"
            placeholder={valuePlaceholder}
            value={p.value}
            onChange={(e) => update(i, 'value', e.target.value)}
          />
          <button type="button" className="btn-secondary px-2" onClick={() => remove(i)}>
            ✕
          </button>
        </div>
      ))}
      <button type="button" className="text-sm text-indigo-600 hover:underline" onClick={add}>
        + adicionar
      </button>
    </div>
  )
}
