// frontend/src/app/pages/workbench-page/rule-builder/rule-builder.component.ts
import { Component, EventEmitter, Input, Output, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { OPERATORS } from '../../../core/models'
import { SPECIAL_FIELDS } from '../../../core/utils/flatten'

const NO_VALUE_OPS = new Set(['exists', 'not_exists', 'is_email_format'])

@Component({
  selector: 'app-rule-builder',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end">
      <div>
        <label class="label">Campo</label>
        <select class="input" [ngModel]="field()" (ngModelChange)="field.set($event)">
          <option value="">Selecione...</option>
          @for (f of specialFields; track f.value) {
            <option [value]="f.value">{{ f.label }}</option>
          }
          @for (f of fieldOptions; track f) {
            <option [value]="f">{{ f }}</option>
          }
          <option value="__custom__">Outro (digitar)...</option>
        </select>
        @if (field() === '__custom__') {
          <input
            class="input mono mt-2"
            placeholder="ex: data.items.0.status"
            [ngModel]="customField()"
            (ngModelChange)="customField.set($event)"
          />
        }
      </div>
      <div>
        <label class="label">Operador</label>
        <select class="input" [ngModel]="operator()" (ngModelChange)="operator.set($event)">
          @for (op of operators; track op.value) {
            <option [value]="op.value">{{ op.label }}</option>
          }
        </select>
      </div>
      <div>
        <label class="label">Valor</label>
        <input
          class="input"
          [disabled]="!needsValue()"
          [placeholder]="needsValue() ? 'ACTIVE' : '(não se aplica)'"
          [ngModel]="value()"
          (ngModelChange)="value.set($event)"
        />
      </div>
      <button class="btn-primary" [disabled]="!effectiveField() || isAdding" (click)="onAddClick()">
        + Adicionar teste
      </button>
    </div>
  `,
})
export class RuleBuilderComponent {
  @Input({ required: true }) fieldOptions: string[] = []
  @Input() isAdding = false
  @Output() add = new EventEmitter<{ field: string; operator: string; expected: string; description: string }>()

  specialFields = SPECIAL_FIELDS
  operators = OPERATORS

  field = signal('')
  customField = signal('')
  operator = signal('equals')
  value = signal('')

  needsValue(): boolean {
    return !NO_VALUE_OPS.has(this.operator())
  }

  effectiveField(): string {
    return this.field() === '__custom__' ? this.customField() : this.field()
  }

  onAddClick() {
    const effectiveField = this.effectiveField()
    const needsValue = this.needsValue()
    this.add.emit({
      field: effectiveField,
      operator: this.operator(),
      expected: this.value(),
      description: `${effectiveField} ${this.operator()} ${needsValue ? this.value() : ''}`.trim(),
    })
    this.value.set('')
  }
}

// frontend/src/components/RuleBuilder.tsx
import { useState } from 'react'
import { OPERATORS } from '../types'
import { SPECIAL_FIELDS } from '../lib/flatten'

export default function RuleBuilder({
  fieldOptions,
  onAdd,
  isAdding,
}: {
  fieldOptions: string[]
  onAdd: (rule: { field: string; operator: string; expected: string; description: string }) => void
  isAdding?: boolean
}) {
  const [field, setField] = useState('')
  const [customField, setCustomField] = useState('')
  const [operator, setOperator] = useState('equals')
  const [value, setValue] = useState('')

  const needsValue = !['exists', 'not_exists', 'is_email_format'].includes(operator)
  const effectiveField = field === '__custom__' ? customField : field

  return (
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-[1fr_1fr_1fr_auto] sm:items-end">
      <div>
        <label className="label">Campo</label>
        <select className="input" value={field} onChange={(e) => setField(e.target.value)}>
          <option value="">Selecione...</option>
          {SPECIAL_FIELDS.map((f) => (
            <option key={f.value} value={f.value}>
              {f.label}
            </option>
          ))}
          {fieldOptions.map((f) => (
            <option key={f} value={f}>
              {f}
            </option>
          ))}
          <option value="__custom__">Outro (digitar)...</option>
        </select>
        {field === '__custom__' && (
          <input
            className="input mono mt-2"
            placeholder="ex: data.items.0.status"
            value={customField}
            onChange={(e) => setCustomField(e.target.value)}
          />
        )}
      </div>
      <div>
        <label className="label">Operador</label>
        <select className="input" value={operator} onChange={(e) => setOperator(e.target.value)}>
          {OPERATORS.map((op) => (
            <option key={op.value} value={op.value}>
              {op.label}
            </option>
          ))}
        </select>
      </div>
      <div>
        <label className="label">Valor</label>
        <input
          className="input"
          disabled={!needsValue}
          placeholder={needsValue ? 'ACTIVE' : '(não se aplica)'}
          value={value}
          onChange={(e) => setValue(e.target.value)}
        />
      </div>
      <button
        className="btn-primary"
        disabled={!effectiveField || isAdding}
        onClick={() => {
          onAdd({
            field: effectiveField,
            operator,
            expected: value,
            description: `${effectiveField} ${operator} ${needsValue ? value : ''}`.trim(),
          })
          setValue('')
        }}
      >
        + Adicionar teste
      </button>
    </div>
  )
}
