// frontend/src/components/NegativeCasesPanel.tsx
import { useMutation } from '@tanstack/react-query'
import { aiSuggestNegativeCases } from '../lib/api'

export default function NegativeCasesPanel({ requestId }: { requestId: string }) {
  const mutation = useMutation({ mutationFn: () => aiSuggestNegativeCases(requestId) })

  return (
    <div>
      <button className="btn-secondary" disabled={mutation.isPending} onClick={() => mutation.mutate()}>
        {mutation.isPending ? 'Analisando...' : '🤖 Sugerir cenários negativos'}
      </button>
      {mutation.data && mutation.data.length === 0 && (
        <p className="mt-2 text-sm text-slate-400">Nenhum cenário negativo óbvio identificado para esta URL.</p>
      )}
      {mutation.data && mutation.data.length > 0 && (
        <ul className="mt-3 space-y-2">
          {mutation.data.map((c) => (
            <li key={c.id} className="rounded-lg border border-slate-200 p-3 text-sm">
              <div className="mb-1 flex items-center gap-2">
                <span className="font-medium text-slate-800">{c.title}</span>
                {c.requires_confirmation ? (
                  <span className="badge bg-amber-100 text-amber-700">requer confirmação — altera dados</span>
                ) : (
                  <span className="badge bg-emerald-100 text-emerald-700">seguro (somente leitura)</span>
                )}
              </div>
              <p className="text-slate-500">{c.description}</p>
            </li>
          ))}
        </ul>
      )}
      <p className="mt-2 text-xs text-slate-400">
        Estas são sugestões de cenários — crie uma nova requisição de teste (com o ID/token indicado) para
        executá-las. Operações que alteram dados (POST/PUT/PATCH/DELETE) nunca disparam automaticamente.
      </p>
    </div>
  )
}

// frontend/src/app/pages/workbench-page/negative-cases-panel/negative-cases-panel.component.ts
import { Component, Input, inject, signal } from '@angular/core'
import { ApiService } from '../../../core/services/api.service'
import type { NegativeCase } from '../../../core/models'

@Component({
  selector: 'app-negative-cases-panel',
  standalone: true,
  template: `
    <div>
      <button class="btn-secondary" [disabled]="pending()" (click)="suggest()">
        {{ pending() ? 'Analisando...' : '🤖 Sugerir cenários negativos' }}
      </button>
      @if (loaded() && cases().length === 0) {
        <p class="mt-2 text-sm text-foreground-muted">Nenhum cenário negativo óbvio identificado para esta URL.</p>
      }
      @if (cases().length > 0) {
        <ul class="mt-3 space-y-2">
          @for (c of cases(); track c.id) {
            <li class="rounded-lg border border-border p-3 text-sm">
              <div class="mb-1 flex items-center gap-2">
                <span class="font-medium text-foreground">{{ c.title }}</span>
                @if (c.requires_confirmation) {
                  <span class="badge bg-warning/15 text-warning">requer confirmação — altera dados</span>
                } @else {
                  <span class="badge bg-success/15 text-success">seguro (somente leitura)</span>
                }
              </div>
              <p class="text-foreground-muted">{{ c.description }}</p>
            </li>
          }
        </ul>
      }
      <p class="mt-2 text-xs text-foreground-muted">
        Estas são sugestões de cenários — crie uma nova requisição de teste (com o ID/token indicado) para
        executá-las. Operações que alteram dados (POST/PUT/PATCH/DELETE) nunca disparam automaticamente.
      </p>
    </div>
  `,
})
export class NegativeCasesPanelComponent {
  private api = inject(ApiService)

  @Input({ required: true }) requestId!: string

  pending = signal(false)
  loaded = signal(false)
  cases = signal<NegativeCase[]>([])

  async suggest() {
    this.pending.set(true)
    try {
      const result = await this.api.aiSuggestNegativeCases(this.requestId)
      this.cases.set(result)
      this.loaded.set(true)
    } finally {
      this.pending.set(false)
    }
  }
}
