// frontend/src/components/AuthEditor.tsx
import type { AuthDef } from '../types'

export default function AuthEditor({ auth, onChange }: { auth: AuthDef; onChange: (auth: AuthDef) => void }) {
  return (
    <div className="space-y-3">
      <div>
        <label className="label">Tipo de autenticação</label>
        <select
          className="input"
          value={auth.type}
          onChange={(e) => onChange({ type: e.target.value as AuthDef['type'] })}
        >
          <option value="none">Nenhuma</option>
          <option value="bearer">Bearer Token</option>
          <option value="basic">Basic Auth</option>
          <option value="api_key">API Key</option>
        </select>
      </div>

      {auth.type === 'bearer' && (
        <div>
          <label className="label">Token</label>
          <input
            className="input mono"
            type="password"
            placeholder="eyJhbGciOi..."
            value={auth.token ?? ''}
            onChange={(e) => onChange({ ...auth, token: e.target.value })}
          />
        </div>
      )}

      {auth.type === 'basic' && (
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="label">Usuário</label>
            <input
              className="input"
              value={auth.username ?? ''}
              onChange={(e) => onChange({ ...auth, username: e.target.value })}
            />
          </div>
          <div>
            <label className="label">Senha</label>
            <input
              className="input"
              type="password"
              value={auth.password ?? ''}
              onChange={(e) => onChange({ ...auth, password: e.target.value })}
            />
          </div>
        </div>
      )}

      {auth.type === 'api_key' && (
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="label">Nome do header/param</label>
            <input
              className="input mono"
              placeholder="X-API-Key"
              value={auth.key_name ?? ''}
              onChange={(e) => onChange({ ...auth, key_name: e.target.value })}
            />
          </div>
          <div>
            <label className="label">Valor</label>
            <input
              className="input mono"
              type="password"
              value={auth.api_key ?? ''}
              onChange={(e) => onChange({ ...auth, api_key: e.target.value })}
            />
          </div>
          <div className="col-span-2">
            <label className="label">Onde enviar</label>
            <select
              className="input"
              value={auth.location ?? 'header'}
              onChange={(e) => onChange({ ...auth, location: e.target.value as 'header' | 'query' })}
            >
              <option value="header">Header</option>
              <option value="query">Query parameter</option>
            </select>
          </div>
        </div>
      )}

      <p className="text-xs text-slate-400">
        🔒 Segredos são criptografados no armazenamento e mascarados na interface — nunca aparecem em texto puro.
      </p>
    </div>
  )
}

// frontend/src/app/shared/auth-editor/auth-editor.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'
import { FormsModule } from '@angular/forms'
import type { AuthDef } from '../../core/models'

@Component({
  selector: 'app-auth-editor',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="space-y-3">
      <div>
        <label class="label">Tipo de autenticação</label>
        <select class="input" [ngModel]="auth.type" (ngModelChange)="setType($event)">
          <option value="none">Nenhuma</option>
          <option value="bearer">Bearer Token</option>
          <option value="basic">Basic Auth</option>
          <option value="api_key">API Key</option>
        </select>
      </div>

      @if (auth.type === 'bearer') {
        <div>
          <label class="label">Token</label>
          <input
            class="input mono"
            type="password"
            placeholder="eyJhbGciOi..."
            [ngModel]="auth.token ?? ''"
            (ngModelChange)="setField('token', $event)"
          />
        </div>
      }

      @if (auth.type === 'basic') {
        <div class="grid grid-cols-2 gap-3">
          <div>
            <label class="label">Usuário</label>
            <input class="input" [ngModel]="auth.username ?? ''" (ngModelChange)="setField('username', $event)" />
          </div>
          <div>
            <label class="label">Senha</label>
            <input
              class="input"
              type="password"
              [ngModel]="auth.password ?? ''"
              (ngModelChange)="setField('password', $event)"
            />
          </div>
        </div>
      }

      @if (auth.type === 'api_key') {
        <div class="grid grid-cols-2 gap-3">
          <div>
            <label class="label">Nome do header/param</label>
            <input
              class="input mono"
              placeholder="X-API-Key"
              [ngModel]="auth.key_name ?? ''"
              (ngModelChange)="setField('key_name', $event)"
            />
          </div>
          <div>
            <label class="label">Valor</label>
            <input
              class="input mono"
              type="password"
              [ngModel]="auth.api_key ?? ''"
              (ngModelChange)="setField('api_key', $event)"
            />
          </div>
          <div class="col-span-2">
            <label class="label">Onde enviar</label>
            <select class="input" [ngModel]="auth.location ?? 'header'" (ngModelChange)="setField('location', $event)">
              <option value="header">Header</option>
              <option value="query">Query parameter</option>
            </select>
          </div>
        </div>
      }

      <p class="text-xs text-foreground-muted">
        🔒 Segredos são criptografados no armazenamento e mascarados na interface — nunca aparecem em texto puro.
      </p>
    </div>
  `,
})
export class AuthEditorComponent {
  @Input({ required: true }) auth: AuthDef = { type: 'none' }
  @Output() authChange = new EventEmitter<AuthDef>()

  setType(type: AuthDef['type']) {
    this.authChange.emit({ type })
  }

  setField<K extends keyof AuthDef>(key: K, value: AuthDef[K]) {
    this.authChange.emit({ ...this.auth, [key]: value })
  }
}
