// frontend/src/app/pages/requests-page/requests-page.component.ts
import { Component, inject, signal } from '@angular/core'
import { ActivatedRoute, Router, RouterLink } from '@angular/router'
import { ApiService } from '../../core/services/api.service'
import { MethodBadgeComponent } from '../../shared/method-badge/method-badge.component'
import type { RequestDef } from '../../core/models'

@Component({
  selector: 'app-requests-page',
  standalone: true,
  imports: [RouterLink, MethodBadgeComponent],
  template: `
    <div>
      <div class="mb-6 flex items-center justify-between">
        <div>
          <a routerLink="/" class="text-sm text-foreground-muted hover:text-foreground">← Projetos</a>
          <h1 class="text-2xl font-bold text-foreground">APIs testadas neste projeto</h1>
        </div>
        <button class="btn-primary" (click)="goNew()">🚀 Testar nova API</button>
      </div>

      @if (isLoading()) {
        <p class="text-foreground-muted">Carregando...</p>
      }

      @if (!isLoading() && requests().length === 0) {
        <div class="card p-10 text-center text-foreground-muted">Nenhuma API testada ainda neste projeto.</div>
      }

      <ul class="space-y-2">
        @for (r of requests(); track r.id) {
          <li class="card flex items-center justify-between p-4 transition-colors hover:border-primary/50">
            <a
              [routerLink]="['/projects', projectId, 'requests', r.id]"
              class="flex flex-1 items-center gap-3 overflow-hidden"
            >
              <app-method-badge [method]="r.method" />
              <div class="min-w-0">
                <p class="truncate font-medium text-foreground">{{ r.name }}</p>
                <p class="truncate text-xs text-foreground-muted mono">{{ r.url }}</p>
              </div>
            </a>
            <div class="flex items-center gap-3">
              @if (r.last_status_code) {
                <span class="badge {{ r.last_status_code < 400 ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger' }}">
                  HTTP {{ r.last_status_code }}
                </span>
              }
              <button class="text-xs text-foreground-muted hover:text-danger" (click)="onDelete(r)">excluir</button>
            </div>
          </li>
        }
      </ul>
    </div>
  `,
})
export class RequestsPageComponent {
  private api = inject(ApiService)
  private route = inject(ActivatedRoute)
  private router = inject(Router)

  projectId = this.route.snapshot.paramMap.get('projectId')!
  requests = signal<RequestDef[]>([])
  isLoading = signal(true)

  constructor() {
    this.reload()
  }

  private reload() {
    this.isLoading.set(true)
    this.api
      .listRequests(this.projectId)
      .then((requests) => this.requests.set(requests))
      .finally(() => this.isLoading.set(false))
  }

  goNew() {
    this.router.navigate(['/projects', this.projectId, 'new'])
  }

  async onDelete(r: RequestDef) {
    if (!confirm(`Excluir "${r.name}"?`)) return
    await this.api.deleteRequest(r.id)
    this.reload()
  }
}

// frontend/src/pages/RequestsPage.tsx
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { deleteRequest, listRequests } from '../lib/api'
import MethodBadge from '../components/MethodBadge'

export default function RequestsPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const { data: requests, isLoading } = useQuery({
    queryKey: ['requests', projectId],
    queryFn: () => listRequests(projectId!),
    enabled: !!projectId,
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => deleteRequest(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['requests', projectId] }),
  })

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <Link to="/" className="text-sm text-slate-400 hover:text-slate-600">
            ← Projetos
          </Link>
          <h1 className="text-2xl font-bold text-slate-900">APIs testadas neste projeto</h1>
        </div>
        <button className="btn-primary" onClick={() => navigate(`/projects/${projectId}/new`)}>
          🚀 Testar nova API
        </button>
      </div>

      {isLoading && <p className="text-slate-400">Carregando...</p>}

      {!isLoading && requests?.length === 0 && (
        <div className="card p-10 text-center text-slate-400">Nenhuma API testada ainda neste projeto.</div>
      )}

      <ul className="space-y-2">
        {requests?.map((r) => (
          <li key={r.id} className="card flex items-center justify-between p-4 hover:border-indigo-300">
            <Link
              to={`/projects/${projectId}/requests/${r.id}`}
              className="flex flex-1 items-center gap-3 overflow-hidden"
            >
              <MethodBadge method={r.method} />
              <div className="min-w-0">
                <p className="truncate font-medium text-slate-900">{r.name}</p>
                <p className="truncate text-xs text-slate-500 mono">{r.url}</p>
              </div>
            </Link>
            <div className="flex items-center gap-3">
              {r.last_status_code && (
                <span
                  className={
                    r.last_status_code < 400
                      ? 'badge bg-emerald-100 text-emerald-700'
                      : 'badge bg-rose-100 text-rose-700'
                  }
                >
                  HTTP {r.last_status_code}
                </span>
              )}
              <button
                className="text-xs text-slate-400 hover:text-rose-600"
                onClick={() => {
                  if (confirm(`Excluir "${r.name}"?`)) deleteMutation.mutate(r.id)
                }}
              >
                excluir
              </button>
            </div>
          </li>
        ))}
      </ul>
    </div>
  )
}
