// frontend/src/components/MethodBadge.tsx
const COLORS: Record<string, string> = {
  GET: 'bg-emerald-100 text-emerald-700',
  POST: 'bg-amber-100 text-amber-700',
  PUT: 'bg-sky-100 text-sky-700',
  PATCH: 'bg-sky-100 text-sky-700',
  DELETE: 'bg-rose-100 text-rose-700',
}

export default function MethodBadge({ method }: { method: string }) {
  const cls = COLORS[method.toUpperCase()] ?? 'bg-slate-100 text-slate-600'
  return <span className={`badge ${cls} mono font-semibold`}>{method.toUpperCase()}</span>
}

// frontend/src/app/shared/method-badge/method-badge.component.ts
import { Component, Input } from '@angular/core'

const COLORS: Record<string, string> = {
  GET: 'bg-success/15 text-success',
  POST: 'bg-warning/15 text-warning',
  PUT: 'bg-accent/15 text-accent',
  PATCH: 'bg-accent/15 text-accent',
  DELETE: 'bg-danger/15 text-danger',
}

@Component({
  selector: 'app-method-badge',
  standalone: true,
  template: `<span class="badge {{ cls() }} mono font-semibold">{{ method.toUpperCase() }}</span>`,
})
export class MethodBadgeComponent {
  @Input({ required: true }) method = ''

  cls(): string {
    return COLORS[this.method.toUpperCase()] ?? 'bg-card-hover text-foreground-muted'
  }
}
